apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: critical-priority
value: 1000000
preemptionPolicy: Never
globalDefault: false
description: "This priority class should be used for platform pods only."

